include:
  - project: "gitlab/default-pipelines"
    file: "/gitlab-ci/PyPi.gitlab-ci.yml"

test:
  stage: test
  image: python:3.12
  before_script:
    - export GITHUB_TOKEN=$GITHUB_TOKEN
    - export GITLAB_TOKEN=$GITLAB_TOKEN
    - pip install -r requirements.txt

  script:
    - pytest -vv
